import figlet from "figlet";
import { writeFileSync } from "fs";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));

const art = figlet
  .textSync("TORCHLEET", { font: "ANSI Shadow" })
  .split("\n")
  .map((l) => l.trimEnd())
  .join("\n");

const escaped = art.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$/g, "\\$");

const output = `// Auto-generated by scripts/generate-ascii.mjs - do not edit manually
// Regenerate: npm run generate-ascii
export const ASCII_ART = \`${escaped}\`;
`;

const outPath = resolve(__dirname, "../src/lib/ascii-art.ts");
writeFileSync(outPath, output);
console.log("Wrote", outPath);
