// GENERATED by scripts/generate.py — do not edit.
// Authored hints from the grader specs, so the tutor and `torchleet.hint()`
// give the same answer. Keyed by slug and by legacy id.

export const authoredHints: Record<string, string[]> = {
 "lin-regression": [
  "A single nn.Linear(1, 1) is the whole model.",
  "forward() just applies that layer to the input.",
  "Train with MSELoss and an SGD/Adam optimizer."
 ],
 "v1-1": [
  "A single nn.Linear(1, 1) is the whole model.",
  "forward() just applies that layer to the input.",
  "Train with MSELoss and an SGD/Adam optimizer."
 ],
 "custom-dataset": [
  "Subclass torch.utils.data.Dataset and implement __len__ and __getitem__.",
  "Read the file once in __init__ and keep X and y as float32 tensors; __getitem__ should just index them.",
  "__getitem__(i) returns the pair (X[i], y[i]) — DataLoader stacks those into batches for you, so do not batch inside the Dataset."
 ],
 "v1-2": [
  "Subclass torch.utils.data.Dataset and implement __len__ and __getitem__.",
  "Read the file once in __init__ and keep X and y as float32 tensors; __getitem__ should just index them.",
  "__getitem__(i) returns the pair (X[i], y[i]) — DataLoader stacks those into batches for you, so do not batch inside the Dataset."
 ],
 "custom-activation": [
  "An activation is just a function of the tensor; you can write it inline or as an nn.Module.",
  "Make sure it is differentiable — use torch ops, not Python branching on tensor values.",
  "Apply it between the linear layers in forward()."
 ],
 "v1-3": [
  "An activation is just a function of the tensor; you can write it inline or as an nn.Module.",
  "Make sure it is differentiable — use torch ops, not Python branching on tensor values.",
  "Apply it between the linear layers in forward()."
 ],
 "custom-loss": [
  "Huber is quadratic for small errors and linear for large ones.",
  "The switch happens at |error| == delta.",
  "0.5*e^2 below the threshold; delta*(|e| - 0.5*delta) above it."
 ],
 "v1-4": [
  "Huber is quadratic for small errors and linear for large ones.",
  "The switch happens at |error| == delta.",
  "0.5*e^2 below the threshold; delta*(|e| - 0.5*delta) above it."
 ],
 "custom-dnn": [
  "Stack Linear layers with a nonlinearity between them.",
  "Without an activation between layers the whole stack collapses to one linear map.",
  "The last layer's out_features is your output dimension."
 ],
 "v1-5": [
  "Stack Linear layers with a nonlinearity between them.",
  "Without an activation between layers the whole stack collapses to one linear map.",
  "The last layer's out_features is your output dimension."
 ],
 "tensorboard": [
  "The model itself is a plain nn.Linear(1, 1).",
  "Log with writer.add_scalar('Loss/train', loss.item(), step).",
  "Run `tensorboard --logdir=runs` to view it."
 ],
 "v1-6": [
  "The model itself is a plain nn.Linear(1, 1).",
  "Log with writer.add_scalar('Loss/train', loss.item(), step).",
  "Run `tensorboard --logdir=runs` to view it."
 ],
 "cnn": [
  "CIFAR-10 images are 3x32x32 and there are 10 classes.",
  "Track the spatial size through each pool: 32 -> 16 after one 2x2 pool.",
  "The first Linear needs in_features = channels * height * width after flattening."
 ],
 "v1-8": [
  "CIFAR-10 images are 3x32x32 and there are 10 classes.",
  "Track the spatial size through each pool: 32 -> 16 after one 2x2 pool.",
  "The first Linear needs in_features = channels * height * width after flattening."
 ],
 "rnn": [
  "The input is (batch, seq_len, input_size) — nn.RNN needs batch_first=True to read it that way.",
  "Feed only the final hidden state into the fully connected layer; that is the summary of the whole sequence.",
  "The output should be (batch, 1): one predicted next value per sequence, not one per timestep."
 ],
 "v1-9": [
  "The input is (batch, seq_len, input_size) — nn.RNN needs batch_first=True to read it that way.",
  "Feed only the final hidden state into the fully connected layer; that is the summary of the whole sequence.",
  "The output should be (batch, 1): one predicted next value per sequence, not one per timestep."
 ],
 "benchmark": [
  "Flatten the 28x28 image before the first Linear layer.",
  "Use time.perf_counter() around the epoch, not time.time().",
  "On CUDA you must torch.cuda.synchronize() before stopping the clock."
 ],
 "v1-11": [
  "Flatten the 28x28 image before the first Linear layer.",
  "Use time.perf_counter() around the epoch, not time.time().",
  "On CUDA you must torch.cuda.synchronize() before stopping the clock."
 ],
 "autoencoder": [
  "The decoder must undo the encoder's downsampling, so the output matches the input shape.",
  "ConvTranspose2d with stride=2 doubles the spatial size; output_padding fixes off-by-ones.",
  "Train it to reconstruct its own input with MSELoss."
 ],
 "v1-12": [
  "The decoder must undo the encoder's downsampling, so the output matches the input shape.",
  "ConvTranspose2d with stride=2 doubles the spatial size; output_padding fixes off-by-ones.",
  "Train it to reconstruct its own input with MSELoss."
 ],
 "quantize-lm": [
  "LanguageModel(vocab_size, embed_size, hidden_size, num_layers): Embedding -> LSTM(batch_first=True) -> Linear -> Softmax.",
  "Predict the *next* token, so take the last timestep of the LSTM output (lstm_out[:, -1, :]) before the Linear — the result is (batch, vocab_size).",
  "torch.ao.quantization.quantize_dynamic(model, {nn.Linear, nn.LSTM}, dtype=torch.qint8) only rewrites modules it recognises, so build the model out of nn.Linear / nn.LSTM rather than raw matmuls."
 ],
 "v1-13": [
  "LanguageModel(vocab_size, embed_size, hidden_size, num_layers): Embedding -> LSTM(batch_first=True) -> Linear -> Softmax.",
  "Predict the *next* token, so take the last timestep of the LSTM output (lstm_out[:, -1, :]) before the Linear — the result is (batch, vocab_size).",
  "torch.ao.quantization.quantize_dynamic(model, {nn.Linear, nn.LSTM}, dtype=torch.qint8) only rewrites modules it recognises, so build the model out of nn.Linear / nn.LSTM rather than raw matmuls."
 ],
 "cnn-param-init": [
  "config_init returns the initializer *function*, it does not run it — you use it as `model.apply(config_init('xavier'))`.",
  "Each initializer takes one module and should only touch it when it is an nn.Conv2d or nn.Linear; apply() walks containers and activations too.",
  "torch.nn.init has all four: zeros_, normal_, xavier_normal_ (variance 1/n) and kaiming_normal_ (variance 2/n). Do not forget the bias."
 ],
 "v1-15": [
  "config_init returns the initializer *function*, it does not run it — you use it as `model.apply(config_init('xavier'))`.",
  "Each initializer takes one module and should only touch it when it is an nn.Conv2d or nn.Linear; apply() walks containers and activations too.",
  "torch.nn.init has all four: zeros_, normal_, xavier_normal_ (variance 1/n) and kaiming_normal_ (variance 2/n). Do not forget the bias."
 ],
 "cnn-scratch": [
  "Output size is (H + 2*padding - kernel) // stride + 1 per spatial dim.",
  "F.unfold turns sliding windows into columns if you want to avoid Python loops.",
  "Do not forget to add the bias, once per output channel."
 ],
 "v1-16": [
  "Output size is (H + 2*padding - kernel) // stride + 1 per spatial dim.",
  "F.unfold turns sliding windows into columns if you want to avoid Python loops.",
  "Do not forget to add the bias, once per output channel."
 ],
 "lstm": [
  "CustomLSTMModel(input_dim, hidden_units).forward(inputs, H_C=None) returns (predictions, (H, C)) with predictions shaped (batch, seq_len, 1).",
  "Per timestep: i, f, o = sigmoid(...), C~ = tanh(...), C = f*C + i*C~, H = o*tanh(C). Stack every H and push the stack through the Linear.",
  "When H_C is given, start from it instead of a fresh state — that is what makes the model resumable, and zeros (not randn) are the right default."
 ],
 "v1-17": [
  "CustomLSTMModel(input_dim, hidden_units).forward(inputs, H_C=None) returns (predictions, (H, C)) with predictions shaped (batch, seq_len, 1).",
  "Per timestep: i, f, o = sigmoid(...), C~ = tanh(...), C = f*C + i*C~, H = o*tanh(C). Stack every H and push the stack through the Linear.",
  "When H_C is given, start from it instead of a fresh state — that is what makes the model resumable, and zeros (not randn) are the right default."
 ],
 "alexnet": [
  "AlexNet expects 3x224x224 input and ends in a classifier over num_classes.",
  "Five conv layers with max-pooling, then three fully connected layers.",
  "Track the spatial size through each stride and pool to size the first Linear."
 ],
 "v1-18": [
  "AlexNet expects 3x224x224 input and ends in a classifier over num_classes.",
  "Five conv layers with max-pooling, then three fully connected layers.",
  "Track the spatial size through each stride and pool to size the first Linear."
 ],
 "3dcnn": [
  "The input is [B, D, C, W, H]. Fold depth into the batch (view(B*D, C, W, H)) for the 2D backbone, then unfold and permute to [B, C, D, W, H] for Conv3d.",
  "ResNet-18 with its last two children stripped divides W and H by 32, so the ConvTranspose3d stack has to multiply them back by 32 — use kernel/stride (1, k, k) so the depth axis is left alone.",
  "Dice over binary masks is 2*|pred ∩ label| / (|pred| + |label|); finish the network with sigmoid so pred is a probability the overlap can be computed on."
 ],
 "v1-21": [
  "The input is [B, D, C, W, H]. Fold depth into the batch (view(B*D, C, W, H)) for the 2D backbone, then unfold and permute to [B, C, D, W, H] for Conv3d.",
  "ResNet-18 with its last two children stripped divides W and H by 32, so the ConvTranspose3d stack has to multiply them back by 32 — use kernel/stride (1, k, k) so the depth axis is left alone.",
  "Dice over binary masks is 2*|pred ∩ label| / (|pred| + |label|); finish the network with sigmoid so pred is a probability the overlap can be computed on."
 ],
 "custom-autograd": [
  "forward(ctx, x, slope) returns slope * x * sigmoid(x); ctx.save_for_backward whatever the backward pass needs.",
  "d/dx [x*sigmoid(x)] = sigmoid(x) + x*sigmoid(x)*(1 - sigmoid(x)); multiply by slope and by grad_output.",
  "backward must return one gradient per forward input: d/dslope is grad_output * x * sigmoid(x). Keep the slope an nn.Parameter in the model so the optimizer updates it."
 ],
 "v1-22": [
  "forward(ctx, x, slope) returns slope * x * sigmoid(x); ctx.save_for_backward whatever the backward pass needs.",
  "d/dx [x*sigmoid(x)] = sigmoid(x) + x*sigmoid(x)*(1 - sigmoid(x)); multiply by slope and by grad_output.",
  "backward must return one gradient per forward input: d/dslope is grad_output * x * sigmoid(x). Keep the slope an nn.Parameter in the model so the optimizer updates it."
 ],
 "transformer": [
  "Shapes: everything below the model works on (batch, seq_len, embed_dim) and returns the same shape.",
  "In attention, split the last dim into (num_heads, head_dim) and move heads next to the batch: (B, H, T, head_dim). Scale the scores by 1/sqrt(head_dim) before the softmax over the *last* axis.",
  "PositionalEncoding builds a (max_len, d_model) table once with sin(pos/10000^(2i/d)) and cos(...), registers it as a buffer, and forward just adds the first seq_len rows to x."
 ],
 "v1-26": [
  "Shapes: everything below the model works on (batch, seq_len, embed_dim) and returns the same shape.",
  "In attention, split the last dim into (num_heads, head_dim) and move heads next to the batch: (B, H, T, head_dim). Scale the scores by 1/sqrt(head_dim) before the softmax over the *last* axis.",
  "PositionalEncoding builds a (max_len, d_model) table once with sin(pos/10000^(2i/d)) and cos(...), registers it as a buffer, and forward just adds the first seq_len rows to x."
 ],
 "gan": [
  "Generator(input_dim, output_dim) maps a latent vector to one fake sample; Discriminator(input_dim) maps a sample to a single number.",
  "End the generator with Tanh so samples live in [-1, 1], and the discriminator with Sigmoid so its output is a probability BCELoss can take.",
  "When you train the generator do NOT detach the fake batch — the gradient has to flow back through the discriminator into the generator."
 ],
 "v1-27": [
  "Generator(input_dim, output_dim) maps a latent vector to one fake sample; Discriminator(input_dim) maps a sample to a single number.",
  "End the generator with Tanh so samples live in [-1, 1], and the discriminator with Sigmoid so its output is a probability BCELoss can take.",
  "When you train the generator do NOT detach the fake batch — the gradient has to flow back through the discriminator into the generator."
 ],
 "seq-seq": [
  "Encoder(input_dim, embed_dim, hidden_dim, num_layers): nn.Embedding over the source vocabulary, then nn.LSTM(embed_dim, hidden_dim, num_layers, batch_first=True).",
  "forward returns (outputs, (hidden, cell)) — the attention needs every timestep, the decoder needs the final states to start from.",
  "With batch_first=True outputs is (batch, src_len, hidden_dim) while hidden and cell stay (num_layers, batch, hidden_dim)."
 ],
 "v1-28": [
  "Encoder(input_dim, embed_dim, hidden_dim, num_layers): nn.Embedding over the source vocabulary, then nn.LSTM(embed_dim, hidden_dim, num_layers, batch_first=True).",
  "forward returns (outputs, (hidden, cell)) — the attention needs every timestep, the decoder needs the final states to start from.",
  "With batch_first=True outputs is (batch, src_len, hidden_dim) while hidden and cell stay (num_layers, batch, hidden_dim)."
 ],
 "optimizers": [
  "Subclass torch.optim.Optimizer and keep per-parameter state in self.state[p] — it starts as an empty dict, so initialize it on the first step. Do the whole update under @torch.no_grad() with in-place ops (mul_, add_, addcmul_, addcdiv_).",
  "Adam: m = b1*m + (1-b1)*g and v = b2*v + (1-b2)*g^2, then correct both by (1 - beta**step) and update p -= lr * m_hat / (sqrt(v_hat) + eps). AdamW adds p.mul_(1 - lr * weight_decay) applied directly to the parameter — do NOT add weight_decay * p to the gradient, that is L2 regularization and the adaptive denominator rescales it.",
  "Muon: buf = momentum*buf + grad (Nesterov uses grad + momentum*buf as the update), orthogonalize with your newton_schulz, scale by sqrt(max(m,n)/min(m,n)), and only for ndim >= 2 — 1D params get the AdamW fallback. newton_schulz: divide X by its Frobenius norm, then iterate X = a*X + b*(X@X.T)@X + c*(X@X.T)^2@X with a=15/8, b=-5/4, c=3/8."
 ],
 "v1-36": [
  "Subclass torch.optim.Optimizer and keep per-parameter state in self.state[p] — it starts as an empty dict, so initialize it on the first step. Do the whole update under @torch.no_grad() with in-place ops (mul_, add_, addcmul_, addcdiv_).",
  "Adam: m = b1*m + (1-b1)*g and v = b2*v + (1-b2)*g^2, then correct both by (1 - beta**step) and update p -= lr * m_hat / (sqrt(v_hat) + eps). AdamW adds p.mul_(1 - lr * weight_decay) applied directly to the parameter — do NOT add weight_decay * p to the gradient, that is L2 regularization and the adaptive denominator rescales it.",
  "Muon: buf = momentum*buf + grad (Nesterov uses grad + momentum*buf as the update), orthogonalize with your newton_schulz, scale by sqrt(max(m,n)/min(m,n)), and only for ndim >= 2 — 1D params get the AdamW fallback. newton_schulz: divide X by its Frobenius norm, then iterate X = a*X + b*(X@X.T)@X + c*(X@X.T)^2@X with a=15/8, b=-5/4, c=3/8."
 ],
 "flash-attention": [
  "Keep a running max, a running denominator l, and a running output accumulator; on each K/V tile rescale all three by alpha = exp(prev_max - new_max).",
  "Divide the accumulator by l only once, after the loop — not inside it.",
  "L is the logsumexp of the scaled scores: running_max + log(l) at the end.",
  "tl.advance the K and V block pointers each iteration; K's block pointer is already transposed, so it advances along its second axis."
 ],
 "byte-pair-encoder": [
  "get_vocab splits each word into characters plus an end-of-word marker, and counts it.",
  "get_stats counts adjacent symbol pairs weighted by each word's frequency.",
  "A merge replaces every adjacent (a, b) with the single symbol 'ab' — the spelling of each word must not change, only how it is chopped up."
 ],
 "v2-3": [
  "get_vocab splits each word into characters plus an end-of-word marker, and counts it.",
  "get_stats counts adjacent symbol pairs weighted by each word's frequency.",
  "A merge replaces every adjacent (a, b) with the single symbol 'ab' — the spelling of each word must not change, only how it is chopped up."
 ],
 "implement-attention-from-scratch": [
  "scores = q @ k.transpose(-2,-1) / sqrt(d_k), then softmax, then @ v.",
  "Divide by sqrt(d_k) or the softmax saturates as dimension grows.",
  "Masked positions become -inf BEFORE the softmax, not zero after it."
 ],
 "v2-6": [
  "scores = q @ k.transpose(-2,-1) / sqrt(d_k), then softmax, then @ v.",
  "Divide by sqrt(d_k) or the softmax saturates as dimension grows.",
  "Masked positions become -inf BEFORE the softmax, not zero after it."
 ],
 "multi-head-attention": [
  "Project Q/K/V, split d_model into num_heads chunks of d_head, attend, then concatenate.",
  "Reshape to (batch, heads, seq, d_head) with view + transpose(1, 2).",
  "After attention, transpose back and merge the heads before the output projection."
 ],
 "v2-7": [
  "Project Q/K/V, split d_model into num_heads chunks of d_head, attend, then concatenate.",
  "Reshape to (batch, heads, seq, d_head) with view + transpose(1, 2).",
  "After attention, transpose back and merge the heads before the output projection."
 ],
 "grouped-query-attention": [
  "Queries keep all heads; keys and values only have num_query_groups heads.",
  "Repeat each K/V group to cover the query heads that share it (repeat_interleave).",
  "With num_query_groups == num_heads GQA is ordinary multi-head attention."
 ],
 "v2-8": [
  "Queries keep all heads; keys and values only have num_query_groups heads.",
  "Repeat each K/V group to cover the query heads that share it (repeat_interleave).",
  "With num_query_groups == num_heads GQA is ordinary multi-head attention."
 ],
 "sinusoidal-positional-embedding": [
  "Even dimensions get sin, odd dimensions get cos.",
  "The frequency for dimension i is 1 / 10000**(2i/d_model).",
  "It is a fixed function of position — register it as a buffer, not a parameter."
 ],
 "v2-10": [
  "Even dimensions get sin, odd dimensions get cos.",
  "The frequency for dimension i is 1 / 10000**(2i/d_model).",
  "It is a fixed function of position — register it as a buffer, not a parameter."
 ],
 "rotary-positional-embedding": [
  "rotate_half splits the last dim in two and returns (-x2, x1) concatenated.",
  "Rotated q = q*cos + rotate_half(q)*sin — the 2D rotation written elementwise.",
  "cos and sin must broadcast against (batch, heads, seq, dim)."
 ],
 "v2-11": [
  "rotate_half splits the last dim in two and returns (-x2, x1) concatenated.",
  "Rotated q = q*cos + rotate_half(q)*sin — the 2D rotation written elementwise.",
  "cos and sin must broadcast against (batch, heads, seq, dim)."
 ],
 "smollm": [
  "rotate_half splits the last dim in half and returns (-x2, x1) concatenated.",
  "repeat_kv expands each KV head n_rep times *in place* so head i of Q pairs with KV head i // n_rep — expand + reshape, not a plain repeat/tile.",
  "RopeAttention: project, split into num_heads (Q) and kv_heads (K/V), rotate Q and K, repeat_kv the K/V, then scaled dot-product attention plus the additive mask."
 ],
 "v2-12": [
  "rotate_half splits the last dim in half and returns (-x2, x1) concatenated.",
  "repeat_kv expands each KV head n_rep times *in place* so head i of Q pairs with KV head i // n_rep — expand + reshape, not a plain repeat/tile.",
  "RopeAttention: project, split into num_heads (Q) and kv_heads (K/V), rotate Q and K, repeat_kv the K/V, then scaled dot-product attention plus the additive mask."
 ],
 "softmax": [
  "exp() of a large number overflows. What can you subtract without changing the result?",
  "softmax(x) == softmax(x - c) for any constant c. Pick c = max(x) along `dim`.",
  "Keep dims when you take the max and the sum so broadcasting lines up."
 ],
 "v3-1": [
  "exp() of a large number overflows. What can you subtract without changing the result?",
  "softmax(x) == softmax(x - c) for any constant c. Pick c = max(x) along `dim`.",
  "Keep dims when you take the max and the sum so broadcasting lines up."
 ],
 "kmeans": [
  "Alternate two steps: assign each point to its nearest centroid, then move each centroid to the mean of its points.",
  "torch.cdist(data, centroids) gives you all the distances at once.",
  "Stop when the centroids stop moving by more than `tol`."
 ],
 "v3-2": [
  "Alternate two steps: assign each point to its nearest centroid, then move each centroid to the mean of its points.",
  "torch.cdist(data, centroids) gives you all the distances at once.",
  "Stop when the centroids stop moving by more than `tol`."
 ],
 "knn": [
  "torch.cdist gives every test-to-train distance in one call.",
  "topk(..., largest=False) picks the nearest neighbours.",
  "Predict the majority label among those neighbours (torch.mode helps)."
 ],
 "v3-3": [
  "torch.cdist gives every test-to-train distance in one call.",
  "topk(..., largest=False) picks the nearest neighbours.",
  "Predict the majority label among those neighbours (torch.mode helps)."
 ],
 "logistic-regression": [
  "sigmoid(z) = 1 / (1 + exp(-z)).",
  "BCE = -mean(y*log(p) + (1-y)*log(1-p)); clamp p away from 0 and 1 first.",
  "Train with gradient descent on the BCE of sigmoid(Xw + b)."
 ],
 "v3-4": [
  "sigmoid(z) = 1 / (1 + exp(-z)).",
  "BCE = -mean(y*log(p) + (1-y)*log(1-p)); clamp p away from 0 and 1 first.",
  "Train with gradient descent on the BCE of sigmoid(Xw + b)."
 ],
 "contrastive-loss-clip": [
  "L2-normalize both feature sets first (F.normalize(x, dim=-1)); the cosine similarity matrix is then just image_features @ text_features.T.",
  "The positives sit on the diagonal, so the cross-entropy targets are torch.arange(batch_size) — image i must match text i.",
  "Symmetric means both directions: (cross_entropy(logits, labels) + cross_entropy(logits.T, labels)) / 2. Scale the logits by the temperature before the softmax, and keep temperature learnable as a log-temperature."
 ],
 "v3-5": [
  "L2-normalize both feature sets first (F.normalize(x, dim=-1)); the cosine similarity matrix is then just image_features @ text_features.T.",
  "The positives sit on the diagonal, so the cross-entropy targets are torch.arange(batch_size) — image i must match text i.",
  "Symmetric means both directions: (cross_entropy(logits, labels) + cross_entropy(logits.T, labels)) / 2. Scale the logits by the temperature before the softmax, and keep temperature learnable as a log-temperature."
 ],
 "2d-positional-embeddings": [
  "Encode the row and the column separately, then concatenate the two halves.",
  "Each half is a standard 1D sinusoidal embedding of size d_model // 2.",
  "Flatten the grid in row-major order so index r*width + c is position (r, c)."
 ],
 "v3-6": [
  "Encode the row and the column separately, then concatenate the two halves.",
  "Each half is a standard 1D sinusoidal embedding of size d_model // 2.",
  "Flatten the grid in row-major order so index r*width + c is position (r, c)."
 ],
 "top-p-sampling": [
  "Sort probabilities descending, then take the smallest prefix whose cumulative mass >= p.",
  "Always keep at least one token, or a peaked distribution can select nothing.",
  "Renormalize the surviving probabilities before sampling from them."
 ],
 "v3-7": [
  "Sort probabilities descending, then take the smallest prefix whose cumulative mass >= p.",
  "Always keep at least one token, or a peaked distribution can select nothing.",
  "Renormalize the surviving probabilities before sampling from them."
 ],
 "top-k-sampling": [
  "Keep the k largest logits and make the rest impossible to select.",
  "Setting the discarded logits to -inf before the softmax does that cleanly.",
  "torch.topk gives you both the values and their indices."
 ],
 "v3-8": [
  "Keep the k largest logits and make the rest impossible to select.",
  "Setting the discarded logits to -inf before the softmax does that cleanly.",
  "torch.topk gives you both the values and their indices."
 ],
 "beam-search": [
  "Keep each beam as (sequence, cumulative_log_prob) and start from ([start_token], 0.0) — the start token counts towards max_len.",
  "Score a candidate with the RUNNING total: score + log_softmax(logits)[token]. Comparing only the current step's log-prob turns beam search into greedy.",
  "Pool the candidates from every beam into one list, sort by score, keep the top beam_width. At the end return the sequence of the highest-scoring beam."
 ],
 "v3-9": [
  "Keep each beam as (sequence, cumulative_log_prob) and start from ([start_token], 0.0) — the start token counts towards max_len.",
  "Score a candidate with the RUNNING total: score + log_softmax(logits)[token]. Comparing only the current step's log-prob turns beam search into greedy.",
  "Pool the candidates from every beam into one list, sort by score, keep the top beam_width. At the end return the sequence of the highest-scoring beam."
 ],
 "temperature-sampling": [
  "Divide the logits by the temperature before the softmax.",
  "Low temperature sharpens the distribution toward the argmax; high flattens it.",
  "Sample with torch.multinomial on the resulting probabilities."
 ],
 "v3-10": [
  "Divide the logits by the temperature before the softmax.",
  "Low temperature sharpens the distribution toward the argmax; high flattens it.",
  "Sample with torch.multinomial on the resulting probabilities."
 ],
 "lora": [
  "LoRA adds a low-rank detour: output = W@x + (alpha/r) * (x@A)@B.",
  "A is (d_in, rank) and B is (rank, d_out); the base layer's weights are frozen.",
  "Merging means W_new = W_old + scaling * (A@B).T — same maths, one matrix."
 ],
 "v3-11": [
  "LoRA adds a low-rank detour: output = W@x + (alpha/r) * (x@A)@B.",
  "A is (d_in, rank) and B is (rank, d_out); the base layer's weights are frozen.",
  "Merging means W_new = W_old + scaling * (A@B).T — same maths, one matrix."
 ],
 "kv-cache": [
  "The cache holds (batch, heads, seq_len, d_head). What changes as you decode?",
  "update() appends the new K/V along the seq_len dimension (dim=2).",
  "In cached mode you compute Q/K/V for the new token only, then attend over the full cached K/V. No causal mask is needed — the cache only holds the past."
 ],
 "v3-12": [
  "The cache holds (batch, heads, seq_len, d_head). What changes as you decode?",
  "update() appends the new K/V along the seq_len dimension (dim=2).",
  "In cached mode you compute Q/K/V for the new token only, then attend over the full cached K/V. No causal mask is needed — the cache only holds the past."
 ],
 "sliding-window-attention": [
  "Position i may attend to j when |i - j| <= window_size.",
  "Build the mask from pairwise distances: (arange - arange.T).abs() <= window_size.",
  "Masked positions get -inf BEFORE the softmax, not zero after it."
 ],
 "v3-13": [
  "Position i may attend to j when |i - j| <= window_size.",
  "Build the mask from pairwise distances: (arange - arange.T).abs() <= window_size.",
  "Masked positions get -inf BEFORE the softmax, not zero after it."
 ],
 "dpo": [
  "get_batch_logps sums the log-probability of each actual next token in the sequence.",
  "Shift by one: logits at position t predict the token at position t+1.",
  "DPO = -logsigmoid(beta * ((pi_chosen - ref_chosen) - (pi_rejected - ref_rejected)))."
 ],
 "v3-14": [
  "get_batch_logps sums the log-probability of each actual next token in the sequence.",
  "Shift by one: logits at position t predict the token at position t+1.",
  "DPO = -logsigmoid(beta * ((pi_chosen - ref_chosen) - (pi_rejected - ref_rejected)))."
 ],
 "ppo-rlhf": [
  "generate_sequences starts from a BOS token (id = vocab_size), samples one token at a time from Categorical(logits=logits[:, -1, :]), and returns the running input ids so the value model can be scored on the same prefixes.",
  "GAE runs backwards: delta_t = r_t + gamma*V(s_{t+1}) - V(s_t) with V(s_T)=0, then A_t = delta_t + gamma*lam*A_{t+1}.",
  "ppo_step recomputes log-probs for `actions` under the current policy, forms ratio = exp(new - old), and takes min(ratio*A, clamp(ratio, 1-eps, 1+eps)*A). total_loss = -policy_objective + 0.5*value_loss + kl_beta*kl_div."
 ],
 "v3-15": [
  "generate_sequences starts from a BOS token (id = vocab_size), samples one token at a time from Categorical(logits=logits[:, -1, :]), and returns the running input ids so the value model can be scored on the same prefixes.",
  "GAE runs backwards: delta_t = r_t + gamma*V(s_{t+1}) - V(s_t) with V(s_T)=0, then A_t = delta_t + gamma*lam*A_{t+1}.",
  "ppo_step recomputes log-probs for `actions` under the current policy, forms ratio = exp(new - old), and takes min(ratio*A, clamp(ratio, 1-eps, 1+eps)*A). total_loss = -policy_objective + 0.5*value_loss + kl_beta*kl_div."
 ],
 "gradient-checkpointing": [
  "In forward: stash fn on ctx, ctx.save_for_backward(*args), and run fn(*args) inside torch.no_grad() so no intermediate activation is kept.",
  "In backward: detach the saved inputs, requires_grad_ them, re-run fn inside torch.enable_grad(), then torch.autograd.grad(output, inputs, grad_outputs).",
  "backward must return one gradient per forward argument — None for fn itself, then a gradient (or None) for each tensor input."
 ],
 "v3-16": [
  "In forward: stash fn on ctx, ctx.save_for_backward(*args), and run fn(*args) inside torch.no_grad() so no intermediate activation is kept.",
  "In backward: detach the saved inputs, requires_grad_ them, re-run fn inside torch.enable_grad(), then torch.autograd.grad(output, inputs, grad_outputs).",
  "backward must return one gradient per forward argument — None for fn itself, then a gradient (or None) for each tensor input."
 ],
 "mixture-of-experts": [
  "Route each token to its top-k experts and weight their outputs by the gate probabilities.",
  "Renormalize the top-k gate values so each token's weights sum to 1.",
  "The aux loss penalizes imbalance: experts should receive roughly equal token shares."
 ],
 "v3-17": [
  "Route each token to its top-k experts and weight their outputs by the gate probabilities.",
  "Renormalize the top-k gate values so each token's weights sum to 1.",
  "The aux loss penalizes imbalance: experts should receive roughly equal token shares."
 ],
 "speculative-decoding": [
  "Draft phase: sample K tokens from the draft one at a time, keeping the draft probability q(x_i) of each. Verification: ONE target forward over prompt + all K drafts gives every p(x_i) at once.",
  "Accept token i with probability min(1, p(x_i)/q(x_i)). On rejection, stop and sample the replacement from the normalised residual max(0, p - q) — that correction is what keeps the output distribution exactly the target's.",
  "The target logits that score draft token i live at position prompt_len - 1 + i. If all K are accepted you get a free bonus token from position prompt_len + K - 1."
 ],
 "v3-18": [
  "Draft phase: sample K tokens from the draft one at a time, keeping the draft probability q(x_i) of each. Verification: ONE target forward over prompt + all K drafts gives every p(x_i) at once.",
  "Accept token i with probability min(1, p(x_i)/q(x_i)). On rejection, stop and sample the replacement from the normalised residual max(0, p - q) — that correction is what keeps the output distribution exactly the target's.",
  "The target logits that score draft token i live at position prompt_len - 1 + i. If all K are accepted you get a free bonus token from position prompt_len + K - 1."
 ],
 "continuous-batching": [
  "Keep two lists: waiting_queue and active_batch. Each step() fills free slots from the queue first, then runs the model, then evicts whatever finished.",
  "A request is done when it emits eos_token_id OR len(generated_ids) reaches max_gen_len — check both after appending the token.",
  "step() should report whether work remains (active or waiting), so run() can simply loop `while self.step(model): pass`."
 ],
 "v3-19": [
  "Keep two lists: waiting_queue and active_batch. Each step() fills free slots from the queue first, then runs the model, then evicts whatever finished.",
  "A request is done when it emits eos_token_id OR len(generated_ids) reaches max_gen_len — check both after appending the token.",
  "step() should report whether work remains (active or waiting), so run() can simply loop `while self.step(model): pass`."
 ],
 "ddpm": [
  "linear_beta_schedule is torch.linspace(beta_start, beta_end, timesteps) — small betas first, so early steps corrupt slowly.",
  "q_sample is the closed form of the forward process: x_t = sqrt(abar_t)*x_0 + sqrt(1-abar_t)*noise, with abar gathered per sample from t (each row of the batch has its own timestep).",
  "p_sample: mu = (1/sqrt(alpha_t)) * (x_t - beta_t/sqrt(1-abar_t) * eps_pred), then add sqrt(beta_t)*z for t > 0 and nothing at t = 0. p_sample_loop starts at x_T ~ N(0, I) and calls p_sample for t = T-1 ... 0."
 ],
 "v3-20": [
  "linear_beta_schedule is torch.linspace(beta_start, beta_end, timesteps) — small betas first, so early steps corrupt slowly.",
  "q_sample is the closed form of the forward process: x_t = sqrt(abar_t)*x_0 + sqrt(1-abar_t)*noise, with abar gathered per sample from t (each row of the batch has its own timestep).",
  "p_sample: mu = (1/sqrt(alpha_t)) * (x_t - beta_t/sqrt(1-abar_t) * eps_pred), then add sqrt(beta_t)*z for t > 0 and nothing at t = 0. p_sample_loop starts at x_T ~ N(0, I) and calls p_sample for t = T-1 ... 0."
 ],
 "ddim-cfg": [
  "The null/unconditional label is the extra embedding row at index num_classes, so the class embedding table needs num_classes + 1 entries.",
  "CFG: eps = eps_uncond + guidance_scale * (eps_cond - eps_uncond). At guidance_scale = 1 that is exactly eps_cond.",
  "DDIM (eta=0): x0_pred = (x_t - sqrt(1-abar_t)*eps) / sqrt(abar_t), then x_prev = sqrt(abar_prev)*x0_pred + sqrt(1-abar_prev)*eps. No randn anywhere in the step — the only randomness is the initial x_T."
 ],
 "v3-21": [
  "The null/unconditional label is the extra embedding row at index num_classes, so the class embedding table needs num_classes + 1 entries.",
  "CFG: eps = eps_uncond + guidance_scale * (eps_cond - eps_uncond). At guidance_scale = 1 that is exactly eps_cond.",
  "DDIM (eta=0): x0_pred = (x_t - sqrt(1-abar_t)*eps) / sqrt(abar_t), then x_prev = sqrt(abar_prev)*x0_pred + sqrt(1-abar_prev)*eps. No randn anywhere in the step — the only randomness is the initial x_T."
 ],
 "mamba": [
  "Discretize first: A_bar = exp(delta[..., None] * A) and B_bar = delta[..., None] * B[:, :, None, :], both (B, L, D, N).",
  "Then run the recurrence over time with h of shape (B, D, N): h = A_bar[:, t] * h + B_bar[:, t] * x[:, t, :, None], y_t = (h * C[:, t, None, :]).sum(-1).",
  "Two things are easy to lose: the skip connection y = y + D * x, and causality in MambaBlock — Conv1d(padding=d_conv-1) must be truncated back to L so no position sees the future."
 ],
 "v3-22": [
  "Discretize first: A_bar = exp(delta[..., None] * A) and B_bar = delta[..., None] * B[:, :, None, :], both (B, L, D, N).",
  "Then run the recurrence over time with h of shape (B, D, N): h = A_bar[:, t] * h + B_bar[:, t] * x[:, t, :, None], y_t = (h * C[:, t, None, :]).sum(-1).",
  "Two things are easy to lose: the skip connection y = y + D * x, and causality in MambaBlock — Conv1d(padding=d_conv-1) must be truncated back to L so no position sees the future."
 ],
 "vit-mae": [
  "PatchEmbedding is a Conv2d with kernel_size = stride = patch_size, then flatten(2).transpose(1, 2) to get (B, n_patches, embed_dim).",
  "ViT: prepend a learned [CLS] token, add a positional embedding of length n_patches + 1, run the encoder, and return either the CLS row or every token.",
  "MAE: shuffle patch indices with argsort(rand), keep the first int(N*(1-mask_ratio)), encode only those, re-insert mask tokens, unshuffle with ids_restore, and average the squared error over MASKED patches only -- (per_patch_mse * mask).sum() / mask.sum()."
 ],
 "v3-23": [
  "PatchEmbedding is a Conv2d with kernel_size = stride = patch_size, then flatten(2).transpose(1, 2) to get (B, n_patches, embed_dim).",
  "ViT: prepend a learned [CLS] token, add a positional embedding of length n_patches + 1, run the encoder, and return either the CLS row or every token.",
  "MAE: shuffle patch indices with argsort(rand), keep the first int(N*(1-mask_ratio)), encode only those, re-insert mask tokens, unshuffle with ids_restore, and average the squared error over MASKED patches only -- (per_patch_mse * mask).sum() / mask.sum()."
 ],
 "triton-fused-softmax": [
  "Online softmax keeps a running max and running sum in one pass.",
  "When a new max arrives, rescale the accumulated sum by exp(old_max - new_max).",
  "Subtracting the running max before exp() is what keeps it stable on large inputs."
 ],
 "v3-24": [
  "Online softmax keeps a running max and running sum in one pass.",
  "When a new max arrives, rescale the accumulated sum by exp(old_max - new_max).",
  "Subtracting the running max before exp() is what keeps it stable on large inputs."
 ],
 "flash-attention-triton": [
  "Outer loop over Q blocks, inner loop over K,V blocks; the only matrix you ever materialize is the (block_q, block_kv) tile of scores.",
  "Carry running_max, running_sum and running_output per Q block. When a tile raises the max, rescale BOTH the running sum and the running output by exp(old_max - new_max) before adding the tile's contribution.",
  "Normalize once, after the inner loop: output = running_output / running_sum. The last block may be short, so slice with min(start + block, N)."
 ],
 "v3-25": [
  "Outer loop over Q blocks, inner loop over K,V blocks; the only matrix you ever materialize is the (block_q, block_kv) tile of scores.",
  "Carry running_max, running_sum and running_output per Q block. When a tile raises the max, rescale BOTH the running sum and the running output by exp(old_max - new_max) before adding the tile's contribution.",
  "Normalize once, after the inner loop: output = running_output / running_sum. The last block may be short, so slice with min(start + block, N)."
 ],
 "fsdp": [
  "shard() is torch.chunk into world_size pieces (detached clones, since each rank owns its own memory); all_gather() is torch.cat of those pieces.",
  "reduce_scatter is reduce THEN scatter: sum the per-rank full gradients elementwise first, then chunk the sum so rank i keeps chunk i.",
  "forward_on_rank should all-gather the weight and bias shards, run F.linear(x, full_weight, full_bias), and drop the gathered copy afterwards — that release is what makes the memory saving real."
 ],
 "v3-26": [
  "shard() is torch.chunk into world_size pieces (detached clones, since each rank owns its own memory); all_gather() is torch.cat of those pieces.",
  "reduce_scatter is reduce THEN scatter: sum the per-rank full gradients elementwise first, then chunk the sum so rank i keeps chunk i.",
  "forward_on_rank should all-gather the weight and bias shards, run F.linear(x, full_weight, full_bias), and drop the gathered copy afterwards — that release is what makes the memory saving real."
 ],
 "grpo": [
  "Generation: repeat_interleave each prompt group_size times so one prompt's completions sit in a contiguous block, then sample token by token.",
  "Advantages are normalised INSIDE each group: reshape rewards to (num_prompts, group_size), subtract the row mean, divide by the row std + eps. No value model, no global mean.",
  "grpo_loss = -mean(min(ratio*A, clip(ratio, 1-eps, 1+eps)*A)) + beta*KL, with ratio = exp(policy_logps - old_logps) and A broadcast over the tokens of its sequence."
 ],
 "v3-27": [
  "Generation: repeat_interleave each prompt group_size times so one prompt's completions sit in a contiguous block, then sample token by token.",
  "Advantages are normalised INSIDE each group: reshape rewards to (num_prompts, group_size), subtract the row mean, divide by the row std + eps. No value model, no global mean.",
  "grpo_loss = -mean(min(ratio*A, clip(ratio, 1-eps, 1+eps)*A)) + beta*KL, with ratio = exp(policy_logps - old_logps) and A broadcast over the tokens of its sequence."
 ],
 "inference-engine": [
  "The cache stores K and V as (B, heads, seq_len, d_head) and update() concatenates the new step along dim=2. In cached mode you only project the NEW token into q/k/v and attend over the whole cached K/V.",
  "MiniTransformer has to know where it is: when a cache is passed, the positional embedding index for the incoming token is the cache's current seq_len, not 0.",
  "top_p keeps the smallest set of tokens whose cumulative probability reaches top_p: sort descending, cumsum, zero out the tail, RENORMALISE, sample, then map the sampled index back through sorted_indices."
 ],
 "v3-28": [
  "The cache stores K and V as (B, heads, seq_len, d_head) and update() concatenates the new step along dim=2. In cached mode you only project the NEW token into q/k/v and attend over the whole cached K/V.",
  "MiniTransformer has to know where it is: when a cache is passed, the positional embedding index for the incoming token is the cache's current seq_len, not 0.",
  "top_p keeps the smallest set of tokens whose cumulative probability reaches top_p: sort descending, cumsum, zero out the tail, RENORMALISE, sample, then map the sampled index back through sorted_indices."
 ],
 "knowledge-distillation": [
  "Two terms: KL against the temperature-softened teacher, and cross-entropy against the hard labels.",
  "alpha blends them: alpha * soft + (1 - alpha) * hard.",
  "Scale the soft term by temperature**2 so its gradients stay comparable as T changes."
 ],
 "v3-29": [
  "Two terms: KL against the temperature-softened teacher, and cross-entropy against the hard labels.",
  "alpha blends them: alpha * soft + (1 - alpha) * hard.",
  "Scale the soft term by temperature**2 so its gradients stay comparable as T changes."
 ],
 "ring-attention": [
  "ring_step is FlashAttention's inner loop: new_max = max(running_max, S.max(-1)), correction = exp(running_max - new_max), then rescale BOTH the running sum and the running output by that correction before adding the block.",
  "Divide by running_sum only once, at the very end — never inside the loop.",
  "Causal masking is per chunk pair: skip a K,V chunk whose index is greater than the Q chunk's (all future), apply a triangular mask when the indices are equal, and mask nothing when the K,V chunk is in the past."
 ],
 "v3-30": [
  "ring_step is FlashAttention's inner loop: new_max = max(running_max, S.max(-1)), correction = exp(running_max - new_max), then rescale BOTH the running sum and the running output by that correction before adding the block.",
  "Divide by running_sum only once, at the very end — never inside the loop.",
  "Causal masking is per chunk pair: skip a K,V chunk whose index is greater than the Q chunk's (all future), apply a triangular mask when the indices are equal, and mask nothing when the K,V chunk is in the past."
 ],
 "swin-transformer": [
  "window_partition: reshape (B, H, W, C) to (B, H/ws, ws, W/ws, ws, C), permute the two window axes next to each other, then flatten. window_reverse undoes exactly that permutation.",
  "The shifted mask compares region labels: label each pre-shift position by which of the (up-to) 4 wrapped regions it belongs to, roll the label map the same way you roll the features, partition it, and allow a pair only when the two labels match.",
  "The relative position bias is one learned scalar per relative offset: build a (w*w, w*w) index map from (row_i - row_j, col_i - col_j) shifted to be non-negative, gather the table with it, and ADD the result to the attention scores before the softmax."
 ],
 "v3-31": [
  "window_partition: reshape (B, H, W, C) to (B, H/ws, ws, W/ws, ws, C), permute the two window axes next to each other, then flatten. window_reverse undoes exactly that permutation.",
  "The shifted mask compares region labels: label each pre-shift position by which of the (up-to) 4 wrapped regions it belongs to, roll the label map the same way you roll the features, partition it, and allow a pair only when the two labels match.",
  "The relative position bias is one learned scalar per relative offset: build a (w*w, w*w) index map from (row_i - row_j, col_i - col_j) shifted to be non-negative, gather the table with it, and ADD the result to the attention scores before the softmax."
 ]
};

export function getAuthoredHints(id: string): string[] | undefined {
  return authoredHints[id];
}
