// Auto-generated by scripts/generate-ascii.mjs — do not edit manually
// Regenerate: npm run generate-ascii
export const ASCII_ART = ` __________  ___  _______ ____   ______________
/_  __/ __ \\/ _ \\/ ___/ // / /  / __/ __/_  __/
 / / / /_/ / , _/ /__/ _  / /__/ _// _/  / /
/_/  \\____/_/|_|\\___/_//_/____/___/___/ /_/
`;
